[package]
name = "wacky_bag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wacky_traits={path="../wacky_traits"}
my_tuple={path="../my_tuple"}